#if defined  _perkmod2_included_
 #endinput
#endif
#define _perkmod2_included_

native bool perkmod2_IsEnable_Perk_StoppingPower(int client);
native bool perkmod2_IsEnable_Perk_SleightOfHand(int client);
native bool perkmod2_IsEnable_Perk_Pyrotechnician(int client);
native bool perkmod2_IsEnable_Perk_MartialArtist(int client);
native bool perkmod2_IsEnable_Perk_ChristmasGift(int client);
native bool perkmod2_IsEnable_Perk_Unbreakable(int client);
native bool perkmod2_IsEnable_Perk_Spirit(int client);
native bool perkmod2_IsEnable_Perk_HelpingHand(int client);
native bool perkmod2_IsEnable_Perk_PackRat(int client);
native bool perkmod2_IsEnable_Perk_ChemReliant(int client);
native bool perkmod2_IsEnable_Perk_HardToKill(int client);
native bool perkmod2_IsEnable_Perk_ExtremeConditioning(int client);

native int perkmod2_Pyro_OnWeaponFire(int client, char[] weapon);
